app:
    resource: "@AppBundle/Controller/"
    type:     annotation
# app/config/routing.yml
feed:
    path:      /feed
    defaults:  { _controller: AppBundle:Feed:fetch }
map:
    path:      /map
    defaults:  { _controller: AppBundle:Main:render }
    