# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.storage:
        class: AppBundle\Storage\Manager\VariableManager
        arguments: ['@doctrine.orm.entity_manager']
    app.curl:
        class: Curl\Curl
    app.yaml:
        class: Symfony\Component\Yaml\Parser
    app.settingsmanager:
        class: AppBundle\Manager\SettingsManager
        arguments: ['@app.yaml']
    app.feedmanager:
        class: AppBundle\Manager\FeedManager
        arguments: ['@app.stationsfeedmanager', '@app.routefeedmanager']
    app.stationsfeedmanager:
        class: AppBundle\Manager\StationsFeedManager
        arguments: ['@doctrine.orm.entity_manager', '@app.storage', '@app.curl', '@app.settingsmanager']
    app.routefeedmanager:
        class: AppBundle\Manager\RouteFeedManager
        arguments: ['@app.stationsmanager', '@app.settingsmanager', '@app.curl']
    app.stationsmanager:
        class: AppBundle\Manager\StationsManager
        arguments: ['@doctrine.orm.entity_manager']