# src/AppBundle/Resources/config/doctrine/Journey.orm.yml
AppBundle\Entity\Journey:
    type: entity
    table: journey
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        route:
            type: integer
            scale: 6
        sequence:
            type: integer
            scale: 6
        duration:
            type: decimal
            scale: 6