# src/AppBundle/Resources/config/doctrine/Station.orm.yml
AppBundle\Entity\Station:
    type: entity
    table: station
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        code:
            type: string
            length: 5
        latitude:
            type: decimal
            scale: 6
        longitude:
            type: decimal
            scale: 6